ebs-printf: printf/printf.h File Reference
printf.h File Reference
Interface and usage of printf implementation.
#include <stdarg.h>
#include <stdint.h>
#include "config.h"
#include <ds/bytebuf.h>
Enumerations
enum printf_ttype_t { PRINT_TTYPE_STRING = 0 , PRINT_TTYPE_BYTEBUF = 1 }
Functions
int putchar (int c)
int print (void **out, const printf_ttype_t ttype, const char *format, va_list args)
static int vsprintf (char *out, const char *format, va_list args)
static int sprintf (char *out, const char *format,...)
bytebuf Support
This implementation supports ::bytebuf buffers as first-class write targets. If this is undesirable, then the following can be removed and/or reimplemented as needed.
static int vbprintf (bytebuf *buf, const char *format, va_list args)
static int bprintf (bytebuf *buf, const char *format,...)
Detailed Description
Interface and usage of printf implementation.
This printf implementation can be used for embedded applications in small embedded systems. As far as possible, the implementation is pared down to the minimum required to retain core functionality.
The library provides two vprintf-like functions, though not printf itself.
vbprintf() : prints to a ::bytebuf, uses ds/bytebuf library
vsprintf() : prints to a string
Locking is not implemented here. As long as it is correctly invoked, vbprintf() inherits the locking mechanism of bytebuf.h and no more. Besides this, the functions should be sufficiently thread safe as long as the write targets are separate. This has not been tested.
Due to the fairly heavy usage of the stack during execution, this library should be used with care, and sparingly.
Warning
There may be, somewhere in the vbprintf() implementation, a race condition that nukes the buffer if it comes in too fast. As far as is apparant, it only occurs at the rollover boundary, it happens at the very first rollover, is not recoverable, and disappears entirely at slower write speeds. It is entirely possible that the error is a result of the producer not checking for a returned error value. Excercise caution.
Allowed format strings :
%d : signed integer
%ld : signed long integer
%s : string
%x, %X : hexadecimal
%u : unsigned integer
%c : character
%% : escape
Allowed flags:
- : Left justify.
0 : Field is padded with 0's instead of blanks.
See also
printf.c
Definition in file printf.h.
Enumeration Type Documentation
printf_ttype_t
enum printf_ttype_t
Enumerator
PRINT_TTYPE_STRING
PRINT_TTYPE_BYTEBUF
Definition at line 71 of file printf.h.
Function Documentation
bprintf()
static int bprintf (bytebuf * buf, const char * format, ...) inline static
Prints to a ::bytebuf buffer. For direct use, similarly to sprintf.
Parameters
buf Pointer to ::bytebuf buffer to write to.
format format string and args as documented.
Returns
Number of characters printed.
Definition at line 161 of file printf.h.
References vbprintf().
print()
int print (void ** out, const printf_ttype_t ttype, const char * format, va_list args) extern
Declaration of the underlying print implementation. This should not be called directly. The call to this function should usually be inlined by one of the proxy functions.
Parameters
out Pointer to the buffer or string to write to.
ttype Target type, either PRINT_TTYPE_STRING or PRINT_TTYPE_BYTEBUF.
format format string and args as documented.
args variable list from stdarg.h
Returns
Number of characters printed.
Definition at line 272 of file printf.c.
References PAD_RIGHT, PAD_ZERO, PRINT_DEFAULT_FLOAT_PRECISION, PRINT_TTYPE_STRING, printchar(), printfloat(), printi(), printl(), and prints().
Referenced by vbprintf(), and vsprintf().
putchar()
int putchar (int c)
Declaration of a generic putchar implementation. Not used.
Parameters
c Character to write.
Returns
0 for failure, 1 for successful.
Definition at line 48 of file printf.c.
Referenced by printchar().
sprintf()
static int sprintf (char * out, const char * format, ...) inline static
Prints to a string. For direct use, exactly as sprintf.
Parameters
out Pointer to string / array to write to.
format format string and args as documented.
Returns
Number of characters printed.
Definition at line 119 of file printf.h.
References vsprintf().
vbprintf()
static int vbprintf (bytebuf * buf, const char * format, va_list args) inline static
Prints to a ::bytebuf buffer. For use by client libraries which intend to provide printf like interfaces.
Parameters
buf Pointer to ::bytebuf to write to.
format format string and args as documented.
args variable list from stdarg.h
Returns
Number of characters printed.
Definition at line 149 of file printf.h.
References print(), and PRINT_TTYPE_BYTEBUF.
Referenced by bprintf().
vsprintf()
static int vsprintf (char * out, const char * format, va_list args) inline static
Prints to a string. For use by client libraries which intend to provide printf like interfaces.
Parameters
out Pointer to string / array to write to.
format format string and args as documented.
args variable list from stdarg.h
Returns
Number of characters printed.
Definition at line 107 of file printf.h.
References print(), and PRINT_TTYPE_STRING.
Referenced by sprintf().