ebs-printf: printf/printf.c File Reference
printf.c File Reference
Pared down printf implementation for embedded use.
#include <math.h>
#include "printf.h"
Macros
#define PAD_RIGHT 1
#define PAD_ZERO 2
Functions
int putchar (int c)
static int printchar (void **target, const printf_ttype_t ttype, int c)
static int prints (void **out, const printf_ttype_t ttype, const char *string, int width, int pad)
static uint8_t _write_number (char **s, int u, int b, int letbase)
static int printl (void **out, const printf_ttype_t ttype, long i, int b, int sg, int width, int pad, int letbase)
static int printi (void **out, const printf_ttype_t ttype, int i, int b, int sg, int width, int pad, int letbase)
static int printfloat (void **out, const printf_ttype_t ttype, float f, int width, int pad, int precision)
int print (void **out, const printf_ttype_t ttype, const char *format, va_list args)
Detailed Description
Pared down printf implementation for embedded use.
See printf.h for usage documentation. Implementation documentation should be added to this file as some point.
See also
printf.h
Definition in file printf.c.
Macro Definition Documentation
PAD_RIGHT
#define PAD_RIGHT 1
Definition at line 71 of file printf.c.
PAD_ZERO
#define PAD_ZERO 2
Definition at line 72 of file printf.c.
Function Documentation
_write_number()
static uint8_t _write_number (char ** s, int u, int b, int letbase) inline static
Definition at line 102 of file printf.c.
Referenced by printfloat(), printi(), and printl().
print()
int print (void ** out, const printf_ttype_t ttype, const char * format, va_list args)
Declaration of the underlying print implementation. This should not be called directly. The call to this function should usually be inlined by one of the proxy functions.
Parameters
out Pointer to the buffer or string to write to.
ttype Target type, either PRINT_TTYPE_STRING or PRINT_TTYPE_BYTEBUF.
format format string and args as documented.
args variable list from stdarg.h
Returns
Number of characters printed.
Definition at line 272 of file printf.c.
References PAD_RIGHT, PAD_ZERO, PRINT_DEFAULT_FLOAT_PRECISION, PRINT_TTYPE_STRING, printchar(), printfloat(), printi(), printl(), and prints().
Referenced by vbprintf(), and vsprintf().
printchar()
static int printchar (void ** target, const printf_ttype_t ttype, int c) static
Definition at line 52 of file printf.c.
References PRINT_TTYPE_BYTEBUF, PRINT_TTYPE_STRING, and putchar().
Referenced by print(), printfloat(), printi(), printl(), and prints().
printfloat()
static int printfloat (void ** out, const printf_ttype_t ttype, float f, int width, int pad, int precision) static
Definition at line 189 of file printf.c.
References _write_number(), PAD_ZERO, PRINT_BUF_LEN, PRINT_TTYPE_STRING, printchar(), printi(), and prints().
Referenced by print().
printi()
static int printi (void ** out, const printf_ttype_t ttype, int i, int b, int sg, int width, int pad, int letbase) static
Definition at line 152 of file printf.c.
References _write_number(), PAD_ZERO, PRINT_BUF_LEN, printchar(), and prints().
Referenced by print(), and printfloat().
printl()
static int printl (void ** out, const printf_ttype_t ttype, long i, int b, int sg, int width, int pad, int letbase) static
Definition at line 116 of file printf.c.
References _write_number(), PAD_ZERO, PRINT_BUF_LEN, printchar(), and prints().
Referenced by print().
prints()
static int prints (void ** out, const printf_ttype_t ttype, const char * string, int width, int pad) static
Definition at line 74 of file printf.c.
References PAD_RIGHT, PAD_ZERO, and printchar().
Referenced by print(), printfloat(), printi(), and printl().
putchar()
int putchar (int c)
Declaration of a generic putchar implementation. Not used.
Parameters
c Character to write.
Returns
0 for failure, 1 for successful.
Definition at line 48 of file printf.c.
Referenced by printchar().